apiVersion: v1
kind: Service
metadata:
  name: eatonpoc-service
  labels:
    app: eatonpoc-service
spec:
  ports:
  - port: 80
    targetPort: 4000
  type: NodePort
  selector:
    app: eatonpoc
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eatonpoc-replica
  labels:
    app: eatonpoc-replica
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: eatonpoc
    spec:
      containers:
      - name: eatonpoc-container
        image: sravangdocker/eatoniot:dev
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000
